package server;

import Model.Player;
import Model.Room;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import Server.service.ManagerService;
import Server.service.PlayerService;
import Server.service.RoomService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cr4zyb0t
 */
public class MainFrame extends javax.swing.JFrame {

    private DefaultTableModel model;
    
    public MainFrame() {
        try {
            // Thiết lập Look and Feel thành Windows
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setIconImage(new ImageIcon(getClass().getResource("/assets/icon.png")).getImage());
        initComponents();
        startServer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ma sói - Server");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(968, 541));
        setResizable(false);
        getContentPane().setLayout(null);

        btnStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play.png"))); // NOI18N
        btnStart.setText("Start Server");
        btnStart.setFocusable(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(20, 240, 137, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/splash_screen_icon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 133, 133);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 2, 24)); // NOI18N
        jLabel2.setText("Werewolf Online v1.0.0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 140, 201, 29);

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room", "Win"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 210, 452, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 20, 300, 174);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 300, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean started = false; 
    private void startServer(){
        if(!started){
            btnStart.setText("Stop server");
            ManagerService.init();
            model = (DefaultTableModel) mainTable.getModel();
            ManagerService.gI().model = model;
        }
        else{
            model.setRowCount(0);
            ManagerService.gI().model = null;
            ManagerService.stop();
            btnStart.setText("Start server");
        }
        started = !started;
    }
    
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        startServer();
    }//GEN-LAST:event_btnStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RoomService.gI().rooms.forEach(r ->{
            int numBot = 9 - r.players.size();
            for(int i = 0; i < numBot; i++){
                Player p = PlayerService.gI().getBot(i);
                r.players.add(p);
                p.room = r;
            }
            RoomService.gI().reloadPlayer(r);
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
