package Client;

import Client.Session.Service;

/**
 *
 * @author cr4zyb0t
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(860, 502));
        setMinimumSize(new java.awt.Dimension(860, 502));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(390, 400, 360, 148);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(390, 400, 477, 148);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(180, 430, 360, 148);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(-20, 400, 360, 148);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(190, 390, 360, 148);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/splash_screen_icon.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(430, 40, 130, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(200, 20, 530, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(20, 10, 150, 180);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(690, 10, 120, 180);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/role-icon.png"))); // NOI18N
        jButton1.setText("Các vai trò");
        add(jButton1);
        jButton1.setBounds(340, 350, 160, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play.png"))); // NOI18N
        jButton2.setText("Chơi ngay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(340, 250, 160, 40);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/friend.png"))); // NOI18N
        jButton3.setText("Chơi với bạn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(340, 300, 160, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Service.gI().frm.changePanel(new PlayPanel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Service.gI().frm.changePanel(new GameRoom());
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
