package Client;

import Client.Session.Service;
import Client.utils.gui;
import config.Constaint;

/**
 *
 * @author cr4zyb0t
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        String username = "admin";
        if(Utils.StringUtils.isValidUsername(username)){
            Service.gI().init(username, indexAvatar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new javax.swing.JLabel();
        labelIconGame = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnStartGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setLayout(null);

        avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/avatar/avatar_1.jpg"))); // NOI18N
        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });
        add(avatar);
        avatar.setBounds(170, 310, 160, 110);

        labelIconGame.setBackground(new java.awt.Color(51, 51, 51));
        labelIconGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_no_transparent.png"))); // NOI18N
        add(labelIconGame);
        labelIconGame.setBounds(360, 80, 150, 140);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setToolTipText("Nhập username (<13 kí tự từ a-z, 0-9)");
        add(txtUsername);
        txtUsername.setBounds(350, 310, 250, 40);

        btnStartGame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/start.png"))); // NOI18N
        btnStartGame.setText("Vào game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        add(btnStartGame);
        btnStartGame.setBounds(350, 370, 250, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/4.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(250, 110, 350, 200);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/2.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 350, 200);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/4.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(480, 390, 350, 200);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/1.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(490, 260, 350, 200);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/1.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(240, -10, 350, 200);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/2.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(530, 140, 350, 200);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/1.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(510, -10, 350, 200);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/1.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(-30, 90, 350, 200);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/1.png"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(260, 240, 350, 200);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/3.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(140, 390, 350, 200);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/2.png"))); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(0, 220, 350, 200);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/3.png"))); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(260, 350, 350, 200);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/4.png"))); // NOI18N
        add(jLabel13);
        jLabel13.setBounds(-70, 390, 350, 200);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/3.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(-50, 310, 350, 200);
    }// </editor-fold>//GEN-END:initComponents
    
    int indexAvatar = 1;
    
    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        String username = txtUsername.getText();
        if(Utils.StringUtils.isValidUsername(username)){
            Service.gI().init(username, indexAvatar);
        }
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        indexAvatar++;
        if(indexAvatar > 16){
            indexAvatar = 1;
        }
        avatar.setIcon(gui.resizeImage(Constaint.pathRoot + "/assets/avatar/avatar_" + indexAvatar + ".jpg", 75, 75));
    }//GEN-LAST:event_avatarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelIconGame;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
