package Client;

import Client.Session.Service;
import config.Constaint;

/**
 *
 * @author cr4zyb0t
 */
public class PlayPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public PlayPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFindGame = new javax.swing.JButton();
        btnCreateGame = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(860, 502));
        setMinimumSize(new java.awt.Dimension(860, 502));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(390, 400, 360, 148);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(390, 400, 477, 148);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(180, 430, 360, 148);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(-20, 400, 360, 148);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_mountains_day.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(190, 390, 360, 148);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/splash_screen_icon.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(430, 40, 130, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(200, 20, 530, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(20, 10, 150, 180);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assets_images_moon.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(690, 10, 120, 180);

        btnFindGame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btnFindGame.setText("Tìm trận");
        btnFindGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindGameActionPerformed(evt);
            }
        });
        add(btnFindGame);
        btnFindGame.setBounds(340, 230, 160, 40);

        btnCreateGame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/room.png"))); // NOI18N
        btnCreateGame.setText("Tạo phòng");
        btnCreateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGameActionPerformed(evt);
            }
        });
        add(btnCreateGame);
        btnCreateGame.setBounds(340, 290, 160, 40);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(340, 350, 160, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGameActionPerformed
        Service.gI().frm.changePanel(new Create_Room());
    }//GEN-LAST:event_btnCreateGameActionPerformed

    private void btnFindGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindGameActionPerformed
        Service.gI().sendMessage(Constaint.MESSAGE_LOAD_ROOM, null);
        Service.gI().frm.changePanel(new Room_List());
    }//GEN-LAST:event_btnFindGameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Service.gI().frm.changePanel(new HomePanel());
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateGame;
    private javax.swing.JButton btnFindGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
