/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client;

/**
 *
 * @author COMPUTER
 */
public class Wolf_WIN extends javax.swing.JPanel {

    /**
     * Creates new form Village_WIN
     */
    public Wolf_WIN() {
        initComponents();
        int seconds = 3;
        new Thread(()->{
            try{
                for(int i = seconds; i >= 0; i--){
                    labelTime.setText("Trở về sau " + i + "s");
                    Thread.sleep(1000);
                }
            }
            catch(Exception e){}
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();

        jPanel2.setPreferredSize(new java.awt.Dimension(860, 502));
        jPanel2.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/role8.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 90, 248, 239);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(430, 70, 200, 176);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 40, 200, 176);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(650, 210, 200, 176);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(630, 40, 200, 176);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(240, 110, 200, 176);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back_fireworks_avatar_large.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 210, 200, 176);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MA SÓI CHIẾN THẮNG");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(250, 340, 350, 60);

        labelTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setText("Trở về sau 3s");
        jPanel2.add(labelTime);
        labelTime.setBounds(340, 400, 170, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelTime;
    // End of variables declaration//GEN-END:variables
}
